[package]
name = "drow"
version = "0.1.0"
authors = ["Andrew Brinker <me@andrewbrinker.com>"]
description = "An opinionated static site builder."

[dependencies]
clap = "2.25.0"
toml = "0.4.1"
log = "0.3.8"
pretty_env_logger = "0.1.1"
git2 = "0.6.6"
getset = "0.0.5"
