[package]
name = "drow"
version = "0.1.0"
authors = ["Andrew Brinker <me@andrewbrinker.com>"]
description = "An opinionated static site generator."

[dependencies]
clap = "2.16.3"
toml = "0.2.1"
slog = "1.2.1"
slog-scope = "0.2.0"
slog-term = "1.3.2"
git2 = "0.5.0"
hyper = "0.9.11"
