#!/usr/bin/env bash

set -u

main () {
    local build="./.build"
    local assets="./assets"
    local pages="./pages"
    local posts="./posts"
    local static="./static"
    local templates="./templates"

    if [ -d "$build" ]; then
        say "Cleaning previous build out."
        rm -r "$build"
    fi

    say "Creating build directory."
    ensure mkdir -p "$build"

    say "Copying assets."
    ensure cp -r "$assets" "$build"

    say "Copying static files."
    ensure cp -R "$static/." "$build"

    say "Building pages."
    for file in $pages/*; do
        local ident=$(basename $file .md)
        local output="$build/$ident/index.html"

        if [ "$ident" = "index" ]; then
            output="$build/index.html"
        fi

        ensure pandoc --template "$templates/main.html" \
                      -f markdown \
                      -t html \
                      -o "$output" \
                      "$file"
    done
}

say() {
    echo "drow: $1"
}

err() {
    say "$1" >&2
    exit 1
}

need_ok() {
    if [ $? != 0 ]; then err "$1"; fi
}

ensure() {
    "$@"
    need_ok "command failed: $*"
}

main $@ || exit 1

